[package]
name = "dex-adapters"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-trait = "0.1"
common = { path = "../common" }
dashmap = "5.5.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
rust_decimal = "1.35"
rust_decimal_macros = "1.35"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = { version = "0.15.1", features = ["serde_impl"] }

[dev-dependencies]
rust_decimal = "1.32"
rust_decimal_macros = "1.32"
