[package]
name = "config"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
common = { path = "../common" }
detector = { path = "../detector" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
tokio = { version = "1.45.1", features = ["full"] }
