[package]
name = "arb-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../../crates/common" }
core = { path = "../../crates/core" }
dex-adapter-trait = { path = "../../crates/dex-adapter-trait" }
detector = { path = "../../crates/detector" }
executor = { path = "../../crates/executor" }
analytics = { path = "../../crates/analytics" }
market-data-ingestor = { path = "../../crates/market-data-ingestor" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rustls = "0.23.28"
