# Enhanced configuration structure
transaction_stream_config:
  starting_version: null
  indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
  auth_token: "your_token_here"
  request_name_header: "market-data-ingestor"

market_data_config:
  # Data source configuration
  data_source:
    type: "grpc"
    # For file-based replay (RecordedBatch protobuf), uncomment below and adjust path/speed:
    # type: "file"
    # file:
    #   path: "./recordings/mainnet_2024_01.pb"
    #   replay_speed: 1.0  # 1.0 = real-time, 0 = as fast as possible
  
  # Filter configuration
  filters:
    mode: "token_pairs"  # or "token" or "all"
    token_pairs:
      - ["APT", "USDC"]
      - ["APT", "USDT"]
    # OR for single token mode:
    # token: "APT"
  
  # DEX configurations with adapter settings
  dexs:
    - name: "Hyperion"
      module_address: "0x89576037b3cc0b89645ea393a47787bb348272c76d6941c574b053672b848039"
      events:
        swap: "::pool::SwapAfterEvent"
        snapshot: "::pool::PoolSnapshot"
      settings:
        tick_spacing_threshold: 10
    
    - name: "ThalaSwap"
      module_address: "0x48271d39d0b05bd6efca2278f22277d6fcc375504f9839fd73f74ace240861af"
      events:
        swap: "::pool::SwapAfterEvent"
        snapshot: "::pool::PoolSnapshot"
      settings: {}

    - name: "Tapp"
      module_address: "0xtapp_module_address"
      events:
        swap: "::events::Swap"
        snapshot: "::events::PoolSnapshot"
      settings: {}
