[package]
name = "detector"
version = "0.1.0"
edition = "2021"

[dependencies]
# Core dependencies
petgraph = "0.6"
tokio = { version = "1", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
common = { path = "../common" }
rust_decimal = { version = "1.32", features = ["maths"] }
rust_decimal_macros = "1.32"
anyhow = "1.0.86"
futures = "0.3.30"
log = "0.4.22"
async-trait = "0.1.80"
uuid = { version = "1.0", features = ["v4", "serde"] }
prometheus = "0.14"
serde = { version = "1.0", features = ["derive"] }

[features]
default = []


[dev-dependencies]
tokio-stream = "0.1"
market-data-ingestor = { path = "../market-data-ingestor" }
